on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-instances:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2.2'
    - name: Install dependencies
      run: sudo apt-get install \
        libcurl4-openssl-dev 
        libharfbuzz-dev \
        libfribidi-dev \
        libudunits2-dev
    - name: Install GDAL
      run: |
        sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable 
        sudo apt-get update 
        sudo apt-get install libgdal-dev libgeos-dev libproj-dev
    - uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: |
          ${{ secrets.PRIVATE_REPO_KEY }}
    - name: Update portfolio
      run: Rscript update-portfolio.R
    - name: Push changes
      run: |
        git config --global user.name github-actions
        git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
        git remote set-url origin git@github.com:arielreed/portfolio.git
        git checkout main

        cp inst/portfolio-06752260.html docs/index.html
        git add docs/index.html
        git commit -m '[CI] Auto update portfolio' || exit 0
        git push